#!/bin/sh

# Upon request, this file mounts a host directory containing kernel modules

#     Copyright 2002-2007 Massimo Rimondini - Computer Networks Research Group,
#     Roma Tre University.
#
#     This file is part of Netkit.
#
#     Netkit is free software: you can redistribute it and/or modify it under
#     the terms of the GNU General Public License as published by the Free
#     Software Foundation, either version 3 of the License, or (at your option)
#     any later version.
#
#     Netkit is distributed in the hope that it will be useful, but WITHOUT ANY
#     WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
#     FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
#     details.
#
#     You should have received a copy of the GNU General Public License along
#     with Netkit.  If not, see <http://www.gnu.org/licenses/>.

### BEGIN INIT INFO
# Provides:          netkit-mount-modules-dir
# Required-Start:
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start:     S
# Default-Stop:      0 6
# X-Start-Before:    networking netkit-phase1 module-init-tools
# X-Stop-After:      networking netkit-phase1
# Short-Description: Netkit module mount
# Description:       This is a Netkit initialization script. It is intended for
#                    usage inside virtual machines.
### END INIT INFO

case "$1" in
   start) 

MODULES=`cat /proc/cmdline | awk -v FS== -v RS=' ' '{if ($1=="modules") {print $2}}'`

if [ -n "$MODULES" ]; then
   MODULES="$MODULES"/lib/modules
   echo "Mounting kernel modules directory ($MODULES) on /lib/modules/ ..."
   # Write access is needed for depmod in order to work properly
   if [ ! -d /lib/modules ]
   then
       mkdir -p /lib/modules
   fi
   mount none /lib/modules/ -t hostfs -o rw,$MODULES
else
   echo "Modules directory not mounted."
fi

;;
    stop)
      KERNEL_VERSION=`uname -r`
      if [ -f /lib/modules/$KERNEL_VERSION/modules.dep ]; then
         echo "Unmounting /lib/modules..."
         umount /lib/modules
      fi

;;
esac
