.TH LCLEAN 1 2022-08-24 Linux "Netkit-JH Manual"
.SH NAME
lclean \- clean temporary files created after launching a Netkit-JH lab
.SH SYNOPSIS
.B lclean
.RI [ OPTION "]... [" MACHINE ]...
.SH DESCRIPTION
Remove temporary files (that is,
.IR .ready ", " .testdone ", and " readyfor.test " files)"
and filesystems
.RI ( .disk " files)"
created and used by Netkit-JH in a lab directory.
.PP
If invoked with no non-option arguments,
.B lclean
removes temporary files relating to all virtual machines that comprise the lab.
Providing a list of
.I MACHINE
names limits removal of files to those just relating to the specified machines.
The
.I readyfor.test
file is always deleted.
Any invalid
.IR MACHINE s
will be skipped.
.PP
Removal of filesystems
.RI ( .disk " files)"
implies that the corresponding virtual machines' contents are reverted to their
original state when the lab is restarted.
.SH OPTIONS
.SS General options
.TP
.BI \-d " DIR"
Clean up the lab inside
.IR DIR .
By default, the cleaning process takes place in the current directory.
.SS Miscellaneous options
.TP
.B \-\-help
Display a usage message and exit.
.TP
.BR \-v ", " \-\-verbose
Show which files are being deleted.
.TP
.B \-\-version
Output version information and exit.
.SH ENVIRONMENT
.TP
.B NETKIT_HOME
All Netkit-JH commands require that the
.B NETKIT_HOME
variable is set the path of the directory which Netkit-JH is installed in.
.SH FILES
.TP
.RI MACHINE .disk
.TQ
.RI MACHINE .ready
.TQ
.RI MACHINE .testdone
.TQ
.I readyfor.test
Files removed by
.BR lclean .
For more information on what purposes the files serve, see
.BR lstart (1)
and
.BR ltest (1).
.TP
.I lab.conf
Located in the lab directory,
.I lab.conf
is used to get lab information from the special lab variables.
If nonexistent an error will be shown but the core functionality of
.B lclean
will not be affected.
See
.BR lab.conf (5)
for more information.
.TP
.I netkit.conf
.TQ
.BI NETKIT_HOME /netkit.conf.default
Netkit-JH stores its configuration settings inside a file named
.IR netkit.conf ,
which can be placed in up to three locations to change its scope.
The default settings are assigned in
.IR netkit.conf.default ;
the existence of this file is required in order to make Netkit-JH work.
See
.BR netkit.conf (5)
for information about these files.
.SH NOTES
Despite sounding similar,
.B lclean
is completely unrelated in functionality to
.BR vclean (1).
While
.B lclean
removes temporary files inside a lab directory,
.BR vclean (1)
operates on the entire Netkit-JH install by terminating hanging processes,
removing unused sockets and log files,
and restoring network settings changed for tap interfaces.
.SH AUTHORS
.so include/authors.man
.SH "SEE ALSO"
.BR lcrash (1),
.BR lhalt (1),
.BR linfo (1),
.BR lstart (1),
.BR ltest (1),
.BR vclean (1),
.BR lab.conf (5),
.BR netkit.conf (5)
