.TH LCRASH 1 2022-08-24 Linux "Netkit-JH Manual"
.SH NAME
lcrash \- crash machines of a Netkit-JH lab
.SH SYNOPSIS
.B lcrash
.RI [ OPTION "]... [" MACHINE ]...
.SH DESCRIPTION
Forcibly shutdown all running virtual machines of a Netkit-JH lab.
If they were physical machines,
this would roughly correspond to unplugging them from the power socket.
.PP
Unlike
.BR lhalt (1),
.B lcrash
may result in a dirty shutdown where integrity of the virtual machines'
filesystems
.RI ( .disk " files)"
cannot be guaranteed.
Therefore, by default, filesystems are removed.
First, the UML management console client,
.BR uml_mconsole ,
is used to send a
.B halt
signal to the virtual machine.
This is repeated once if it fails.
If the machine is still online, the machine's processes are sent
.B SIGTERM
twice to safely terminate.
If still running, the processes are sent
.B SIGKILL
as a last resort to terminate immediately.
For more information on how machines are terminated, see
.BR vcrash (1),
which is used on each individual machine to shut it down.
.PP
If invoked with no non-option arguments,
.B lcrash
shuts down all virtual machines that comprise the lab.
Providing a list of
.IR MACHINE s
allows the user to be explicit with what machines are shut down.
Any invalid
.I MACHINE
names will be ignored.
.PP
To crash a machine that may not have been launched from a Netkit-JH lab
(or to crash multiple machines from different labs), use
.BR vcrash (1).
.SH OPTIONS
.SS General options
.TP
.BI \-d " DIR"
Crash the lab inside
.IR DIR .
By default, the current directory is used.
.TP
.BR \-l ", " \-\-list
Show a list of virtual machines still running after crashing the lab with
.BR vlist (1).
.SS Options affecting how machines are crashed
.TP
.BR \-F ", " \-\-keep\-fs
Preserve changes to the virtual machines by not deleting machines' filesystems
.RI ( .disk " files)."
By default, the filesystems are deleted.
.TP
.BR \-k ", " \-\-just\-kill
Crash machines as usual but skip the attempts with
.BR uml_mconsole ;
this invokes
.BR vcrash (1)
with
.BR \-\-just\-kill .
The method is generally faster but may corrupt the machines' filesystems
(which is not an issue if
.B \-\-keep\-fs
is not used since they will get deleted).
.TP
.BR \-q ", " \-\-quick
Disable checking if machines have actually terminated.
Like
.BR \-\-just\-kill , 
this option will skip invoking
.B uml_mconsole
however it also does not send a
.B SIGTERM
signal (i.e., only
.B SIGKILL
is used).
.SS Miscellaneous options
.TP
.B \-\-help
Display a usage message and exit.
.TP
.BR \-v ", " \-\-verbose
Show which processes are getting terminated.
.TP
.B \-\-version
Output version information and exit.
.SH ENVIRONMENT
.TP
.B NETKIT_HOME
All Netkit-JH commands require that the
.B NETKIT_HOME
variable is set the path of the directory which Netkit-JH is installed in.
.SH FILES
.TP
.I lab.conf
Located in the lab directory,
.I lab.conf
is used to read the
.B LAB_MACHINES
configuration variable if the user wishes to override the default behaviour of
determining the hostname list from the directory listing.
The file is also used to get lab information from the special lab variables.
If the file is nonexistent, an error will be shown but the core functionality
of
.B lcrash
will not be affected.
See
.BR lab.conf (5)
for more information.
.TP
.I netkit.conf
.TQ
.BI NETKIT_HOME /netkit.conf.default
Netkit-JH stores its configuration settings inside a file named
.IR netkit.conf ,
which can be placed in up to three locations to change its scope.
The default settings are assigned in
.IR netkit.conf.default ;
the existence of this file is required in order to make Netkit-JH work.
See
.BR netkit.conf (5)
for information about these files.
.SH AUTHORS
.so include/authors.man
.SH "SEE ALSO"
.BR lclean (1),
.BR lhalt (1),
.BR linfo (1),
.BR lstart (1),
.BR ltest (1),
.BR vcrash (1),
.BR vlist (1),
.BR lab.conf (5),
.BR netkit.conf (5)
