.TH LINFO 1 2022-08-30 Linux "Netkit-JH Manual"
.SH NAME
linfo \- show information about a Netkit-JH lab
.SH SYNOPSIS
.B linfo
.RI [ OPTION ]...
.SH DESCRIPTION
Display information about a Netkit-JH lab without running it.
Information is extracted from the
.I lab.conf
file and lab directory contents.
Optionally, a PNG file displaying the network's link layer topology can be
generated.
.SH OPTIONS
.SS General options
.TP
.BI \-d " DIR"
Crash the lab inside
.IR DIR .
By default, the current directory is used.
Unlike other lcommands, multiple directories can be specified with repeat
.B \-d
flags.
.TP
.BR \-m ", " \-\-map =\fIFILE\fR
Draw the lab's link layer topology as a PNG to
.IR FILE .
This requires installation of the Graphviz package.
.TP
.BR \-a "[\fIGLOB\fR], " \-\-auto [=\fIGLOB\fR]
Find sibling directores to the current working directory which will be
considered as parts of the same lab. Without an argument, these will be deduced
as folders with the same name as the working directory except the final
character\(emit will match using the parameter expansion
.IR ${PWD%?}*/ .
I.e., a working directory of
.I /home/user/lab3a
will add all directories of the form
.IR /home/user/lab3*
to the lab
.RI ( /home/user/lab3a ", " /home/user/lab3b ", " /home/user/lab3c ", etc)."
.IP
To override the default behaviour, a
.I GLOB
can be provided.
Note: because this argument is optional it must be attached to the short option
.RB ( \-a \fIGLOB\fR)
or separated to the long option with an equals sign
.RB ( \-\-auto =\fIGLOB\fR).
.IP
This option may be used in conjunction with
.BR \-d .
.SS Miscellaneous options
.TP
.B \-\-help
Display a usage message and exit.
.TP
.B \-\-version
Output version information and exit.
.SH ENVIRONMENT
.TP
.B NETKIT_HOME
All Netkit-JH commands require that the
.B NETKIT_HOME
variable is set the path of the directory which Netkit-JH is installed in.
.SH FILES
.TP
.I lab.conf
Located in the lab directory,
.I lab.conf
is used to read the
.B LAB_MACHINES
configuration variable if the user wishes to override the default behaviour of
determining the hostname list from the directory listing.
The file is also used to get lab information from the special lab variables.
If the file is nonexistent,
.B linfo
will be unable to determine the network's topology for
.BR \-\-map .
See
.BR lab.conf (5)
for more information.
.TP
.I lab.dep
Located in the lab directory,
.I lab.dep
is used by
.B linfo
to determine if the lab supports parallel startup.
See
.BR lab.dep (5)
for more information.
.TP
.I netkit.conf
.TQ
.BI NETKIT_HOME /netkit.conf.default
Netkit-JH stores its configuration settings inside a file named
.IR netkit.conf ,
which can be placed in up to three locations to change its scope.
The default settings are assigned in
.IR netkit.conf.default ;
the existence of this file is required in order to make Netkit-JH work.
See
.BR netkit.conf (5)
for information about these files.
.SH AUTHORS
.so include/authors.man
.SH "SEE ALSO"
.BR lclean (1),
.BR lcrash (1),
.BR lhalt (1),
.BR lstart (1),
.BR ltest (1),
.BR lab.conf (5),
.BR lab.dep (5),
.BR netkit.conf (5)
