.TH VCLEAN 1 2022-08-31 Linux "Netkit-JH Manual"
.SH NAME
vclean \- clean up the Netkit-JH install
.SH SYNOPSIS
.B vclean
.RI [ OPTION ]...
.SH DESCRIPTION
Perform a cleanup of the Netkit-JH install by terminating processes,
removing temporary files, and resetting the host's tap configuration.
When invoked without options, the script just removes unused virtual hubs.
.PP
.B vclean
is necessary in situations where labs have been improperly terminated,
network interfaces have been added with
.BR vconf (1),
or a variety of other unforseen issues.
If there is any error encountered without an obvious fix,
the first port of call should be to run this utility;
it should be considered as Netkit-JH's panic button.
.PP
The following functionality is available:
.RS
.IP \[bu] 4
Kill processes associated with unused (or all) virtual hubs.
.IP \[bu]
Kill running virtual machines.
.IP \[bu]
Wipe the
.BR MCONSOLE_DIR ", " HUB_SOCKET_DIR ", and"
.I .netkit/
directories (except the
.I netkit.conf
file).
.IP \[bu]
Remove host-side tap interface configurations.
.RE
.SH OPTIONS
.SS General options
.TP
.BR \-q ", " \-\-quick
Disable checking if processes have actually terminated.
.TP
.B \-\-test
Instead of actually cleaning the install,
just show which operations will be performed.
.TP
.BR \-u ", " \-\-user =\fIUSERNAME\fR
Perform the cleanup operations only on artefacts owned by
.IR USERNAME .
The special username
.B \-
denotes all users; this may require administrative privileges.
.SS Options affecting how the system is cleaned
.TP
.B \-\-clean\-all
Equivalent to running
.nf
.RS
.IP
.BR vclean " " \c
\-\-user=\- \-\-kill\-machines \-\-clean\-directories \-\-remove\-tunnels
.RE
.fi
.IP
This action affects all users.
It is the most successful option in fixing a Netkit-JH install.
.TP
.B \-\-clean\-directories
Wipe the
.BR MCONSOLE_DIR ", " HUB_SOCKET_DIR ", and"
.I .netkit/
directories (except the
.I netkit.conf
file).
This option affects all users if the directories are shared.
.TP
.BR \-f ", " \-\-force
Kill all virtual hubs (not just unused ones).
Should be used with
.B \-\-remove\-hubs
(enabled by default with no other options).
.TP
.BR \-H ", " \-\-remove\-hubs
Kill unused virtual hubs.
This is
.BR vclean 's
default action if no other action has been requested.
.TP
.BR \-K ", " \-\-kill\-machines
Kill all running virtual machines and virtual hubs.
Like
.BR vcrash (1),
the termination may not be clean so any
.I .disk
files may be corrupted.
The \(dqnetkit\(dq tmux server will also be killed for the current user.
.TP
.BR \-T ", " \-\-remove\-tunnels
Remove any \(dqtap\(dq interface configurations.
This involves removing the network interfaces themselves and,
if affecting users
.RI ( \-\-user=- ),
firewall rules for the interfaces' traffic.
This option requires administrative privileges.
.SS Miscellaneous options
.TP
.B \-\-help
Display a usage message and exit.
.TP
.BR \-v ", " \-\-verbose
Show affected artefacts.
.TP
.B \-\-version
Output version information and exit.
.SH ENVIRONMENT
.TP
.B NETKIT_HOME
All Netkit-JH commands require that the
.B NETKIT_HOME
variable is set the path of the directory which Netkit-JH is installed in.
.SH FILES
.TP
.I netkit.conf
.TQ
.BI NETKIT_HOME /netkit.conf.default
Netkit-JH stores its configuration settings inside a file named
.IR netkit.conf ,
which can be placed in up to three locations to change its scope.
The default settings are assigned in
.IR netkit.conf.default ;
the existence of this file is required in order to make Netkit-JH work.
See
.BR netkit.conf (5)
for information about these files.
.SH NOTES
Despite sounding similar,
.B vclean
is completely unrelated in functionality to
.BR lclean (1).
While
.B vclean
operates on the entire Netkit-JH install by terminating hanging processes,
removing unused sockets and log files,
and restoring network settings changed for tap interfaces,
.BR lclean (1)
removes temporary files inside a specific lab directory.
.SH AUTHORS
Netkit-JH is maintained by Adam Bromiley, Joshua Hawking,
and other important contributors who are current or graduate students of WMG,
University of Warwick.
A full list of contributors can be found in copyright notices at the top of
source files.
.PP
Netkit-JH is a fork of the now deprecated Netkit-NG,
maintained by Julien Iguchi-Cartigny of the XLIM Research Institute,
which itself is a fork of the original project (Netkit).
Netkit was written by academics at the Computer Networks Laboratory of Roma Tre
University before being abandoned in favour of Kathará,
which utilises Python and Docker instead of Bash and UML.
All iterations of Netkit have introduced important new features and upgraded
existing ones.
.SH "REPORTING BUGS"
To report a bug with Netkit-JH,
please create an issue with the recommended template on the project's
.UR https://github.com/netkit-jh/netkit-jh-build/issues
GitHub repository
.UE .
For a more complex bug that you know how to fix,
please consider writing a patch and sending it as a pull request to the GitHub.
.SH COPYRIGHT
Like its predecessors,
Netkit-JH is released under the terms of the GNU General Public License,
version 3 or later. For a copy of the license see the included
.I LICENSE.txt
file or, if not present,
.UR http://www.gnu.org/licenses/
.UE .
.SH "SEE ALSO"
.BR lclean (1),
.BR vcrash (1),
.BR netkit.conf (5),
.BR netkit-jh (7)
