.TH VCOMMAND 1 2022-08-31 Linux "Netkit-JH Manual"
.SH NAME
vcommand \- execute a command on a Netkit-JH machine via its tmux session
.SH SYNOPSIS
.B vcommand
.RI [ OPTION "]... " MACHINE " [" COMMAND ]
.SH DESCRIPTION
Send a shell
.I COMMAND
to a running Netkit-JH
.I MACHINE
via its tmux session and send back its output.
The
.I COMMAND
is sent as a string literal to the tmux session with
.BR send\-keys ,
making the user responsible for sufficient argument quoting and escaping.
.PP
.B vcommand
relies on the host having an active tmux session,
so it must have been invoked with a
.B VM_CON0
Netkit-JH variable value of
.B tmux
(possible by setting
.I netkit.conf
appropriately or by using
.BR vstart "'s " \-\-con0 " or " \-\-tmux\-attached / \-\-tmux\-detached ).
Because there is only one shell instance per tmux session,
sending multiple commands at once or when it is attached and being used may
cause undesirable behaviour;
.B send\-keys
provides access to the input of the machine's terminal not an isolated shell.
.SH OPTIONS
.SS General options
.TP
.BR \-n ", " \-\-timeout =\fIN\fR
Wait
.I N
seconds after entering the command before reading its output.
The default value is one second.
If a command takes a while to execute, consider increasing this value.
.SS Miscellaneous options
.TP
.B \-\-help
Display a usage message and exit.
.TP
.BR \-v ", " \-\-verbose
Display debugging messages.
.TP
.B \-\-version
Output version information and exit.
.SH ENVIRONMENT
.TP
.B NETKIT_HOME
All Netkit-JH commands require that the
.B NETKIT_HOME
variable is set the path of the directory which Netkit-JH is installed in.
.SH FILES
.TP
.I netkit.conf
.TQ
.BI NETKIT_HOME /netkit.conf.default
Netkit-JH stores its configuration settings inside a file named
.IR netkit.conf ,
which can be placed in up to three locations to change its scope.
The default settings are assigned in
.IR netkit.conf.default ;
the existence of this file is required in order to make Netkit-JH work.
See
.BR netkit.conf (5)
for information about these files.
.SH AUTHORS
.so include/authors.man
.SH "SEE ALSO"
.BR vconnect (1),
.BR vstart (1),
.BR netkit.conf (5)
