.TH VCONF 1 2022-08-31 Linux "Netkit-JH Manual"
.SH NAME
vconf \- attach network interfaces to a running Netkit-JH machine
.SH SYNOPSIS
.B vconf
.RI [ OPTION "]... " MACHINE
.SH DESCRIPTION
Attach or remove network interfaces to a running Netkit-JH virtual
.IR MACHINE .
.B vconf
uses the UML management console client,
.IR uml_mconsole ,
to send the machine a
.BR config or remove
signal alongside the network interface's configuration data.
.SH OPTIONS
.SS General options
.TP
.BR \-\-eth \fIN\fR=\fIDOMAIN\fR
Add a network interface called
.RI \(dqeth N \(dq,
where
.I N
is a number between 0 and
.BI MAX_INTERFACES \-1
(defined in the Netkit-JH configuration file) inclusive.
.I DOMAIN
is the Netkit-JH collision domain that the interface should be attached to.
\(dqTap\(dq domains may also be created.
If
.I DOMAIN
is an empty string, the interface will removed from the machine.
The syntax for this option is the same as in
.BR vstart ,
so refer to
.BR vstart (1)
for more information.
.TP
.BR \-n ", " \-\-dry\-run ", " \-\-just\-print ", " \-\-recon
Do not actually manage the interfaces of a machine,
just show which commands would be executed.
.TP
.BR \-u ", " \-\-user =\fIUSERNAME\fR
Manage interfaces for a machine owned by a different user.
The special username
.B \-
denotes all users and will cause
.B vconf
to manage the first host reported by
.IR "vlist \-\-user=\- MACHINE" .
By default, interfaces are managed on machines owned by the current user.
.SS Miscellaneous options
.TP
.B \-\-help
Display a usage message and exit.
.TP
.BR \-v ", " \-\-verbose
Show commands being ran.
.TP
.B \-\-version
Output version information and exit.
.SH ENVIRONMENT
.TP
.B NETKIT_HOME
All Netkit-JH commands require that the
.B NETKIT_HOME
variable is set the path of the directory which Netkit-JH is installed in.
.SH FILES
.TP
.I netkit.conf
.TQ
.BI NETKIT_HOME /netkit.conf.default
Netkit-JH stores its configuration settings inside a file named
.IR netkit.conf ,
which can be placed in up to three locations to change its scope.
The default settings are assigned in
.IR netkit.conf.default ;
the existence of this file is required in order to make Netkit-JH work.
See
.BR netkit.conf (5)
for information about these files.
.SH AUTHORS
.so include/authors.man
.SH "SEE ALSO"
.BR vlist (1),
.BR vstart (1),
.BR lab.conf (5),
.BR netkit.conf (5)
