.TH VCONNECT 1 2022-08-31 Linux "Netkit-JH Manual"
.SH NAME
vconnect \- attach to the tmux session of a running Netkit-JH machine
.SH SYNOPSIS
.B vconnect
.RI [ OPTION "]... " MACHINE ...
.SH DESCRIPTION
Attach to the tmux session of a Netkit-JH machine or terminate an existing one.
Like
.BR vcommand (1),
.B vconnect
relies on the running machine having an active tmux session;
it should have been launched with a
.B VM_CON0
Netkit-JH variable value of
.B tmux
(possible by setting
.I netkit.conf
appropriately or by using
.BR vstart "'s " \-\-con0 " or " \-\-tmux\-attached / \-\-tmux\-detached ).
.SH OPTIONS
.SS General options
.TP
.BR \-l ", " \-\-list
List all running sessions on the \(dqnetkit\(dq tmux server.
.TP
.BR \-k ", " \-\-kill
Terminate the
.IR MACHINE 's
already-running tmux session (if exists).
.TP
.B \-\-kill\-all
Terminate all running sessions on the \(dqnetkit\(dq tmux server.
.SS Options affecting how a session is attached to
.TP
.BR \-t ", " \-\-terminal
Connect to the tmux session in a new terminal window.
The terminal emulator used depends on the
.B TERM_TYPE
Netkit-JH configuration variable.
.TP
.BR \-r ", " \-\-retry\-count =\fIN\fR
Maximum number of connection attempts that should be made.
.TP
.BR \-n ", " \-\-interval =\fIN\fR
Number of seconds to wait between successive connection attempts.
.SS Miscellaneous options
.TP
.B \-\-help
Display a usage message and exit.
.TP
.B \-\-version
Output version information and exit.
.SH ENVIRONMENT
.TP
.B NETKIT_HOME
All Netkit-JH commands require that the
.B NETKIT_HOME
variable is set the path of the directory which Netkit-JH is installed in.
.SH FILES
.TP
.I netkit.conf
.TQ
.BI NETKIT_HOME /netkit.conf.default
Netkit-JH stores its configuration settings inside a file named
.IR netkit.conf ,
which can be placed in up to three locations to change its scope.
The default settings are assigned in
.IR netkit.conf.default ;
the existence of this file is required in order to make Netkit-JH work.
See
.BR netkit.conf (5)
for information about these files.
.SH AUTHORS
.so include/authors.man
.SH "SEE ALSO"
.BR vcommand (1),
.BR vstart (1),
.BR netkit.conf (5)
