.TH VCRASH 1 2022-09-01 Linux "Netkit-JH Manual"
.SH NAME
vcrash \- crash running Netkit-JH machines
.SH SYNOPSIS
.B vcrash
.RI [ OPTION "]... " MACHINE ...
.SH DESCRIPTION
Forcibly shutdown running Netkit-JH
.IR MACHINE s.
If they were physical machines,
this would roughly correspond to unplugging them from the power socket.
Any invalid
.I MACHINE
names will be ignored.
.PP
Unlike
.BR vhalt (1),
.B vcrash
may result in a dirty shutdown where integrity of the virtual machines'
filesystems
.RI ( .disk " files)"
cannot be guaranteed.
Therefore, by default, filesystems are removed.
First, the UML management console client,
.BR uml_mconsole ,
is used to send a
.B halt
signal to the virtual machine.
This is repeated once if it fails.
If the machine is still online, the machine's processes are sent
.B SIGTERM
twice to safely terminate.
If still running, the processes are sent
.B SIGKILL
as a last resort to terminate immediately.
.PP
To crash an entire Netkit-JH lab, use
.BR lcrash (1).
.SH OPTIONS
.SS General options
.TP
.B \-\-test
Do not actually crash the machines,
just show which processes will be affected.
.TP
.BR \-u ", " \-\-user =\fIUSERNAME\fR
Crash machines owned by a different user.
The special username
.B \-
denotes all users and will cause
.B vcrash
to shutdown the first host reported by
.IR "vlist \-\-user=\- MACHINE" .
By default, machines owned by the current user are targetted.
.SS Options affecting how machines are crashed
.TP
.BR \-F ", " \-\-keep\-fs
Preserve changes to the virtual machines by not deleting machines' filesystems
.RI ( .disk " files)."
By default,
.B vcrash
removes the filesystems.
.TP
.BR \-k ", " \-\-just\-kill
Crash machines as usual but skip the attempts with
.BR uml_mconsole .
The method is generally faster but may corrupt the machines' filesystems
(which is not an issue if
.B \-\-keep\-fs
is not used since they will get deleted).
.TP
.BR \-q ", " \-\-quick
Disable checking if machines have actually terminated.
Like
.BR \-\-just\-kill , 
this option will skip invoking
.B uml_mconsole
however it also does not send a
.B SIGTERM
signal (i.e., only
.B SIGKILL
is used).
.SS Miscellaneous options
.TP
.B \-\-help
Display a usage message and exit.
.TP
.BR \-v ", " \-\-verbose
Show which processes are getting terminated.
.TP
.B \-\-version
Output version information and exit.
.SH ENVIRONMENT
.TP
.B NETKIT_HOME
All Netkit-JH commands require that the
.B NETKIT_HOME
variable is set the path of the directory which Netkit-JH is installed in.
.SH FILES
.TP
.I netkit.conf
.TQ
.BI NETKIT_HOME /netkit.conf.default
Netkit-JH stores its configuration settings inside a file named
.IR netkit.conf ,
which can be placed in up to three locations to change its scope.
The default settings are assigned in
.IR netkit.conf.default ;
the existence of this file is required in order to make Netkit-JH work.
See
.BR netkit.conf (5)
for information about these files.
.SH AUTHORS
.so include/authors.man
.SH "SEE ALSO"
.BR lcrash (1),
.BR vhalt (1),
.BR vlist (1),
.BR vstart (1),
.BR netkit.conf (5)
