.TH VDUMP 1 2022-09-01 Linux "Netkit-JH Manual"
.SH NAME
vdump \- dump packets from a Netkit-JH virtual hub
.SH SYNOPSIS
.B vdump
.I DOMAIN
.SH DESCRIPTION
Dump packets from a Netkit-JH virtual hub as a PCAP file to standard output.
The hub is selected by specifying its collision domain name (value of
.BR vstart (1)'s
.BI \-\-eth N
option or declared in
.IR lab.conf ).
.PP
.B vdump
works as a wrapper around
.BR uml_dump ,
which itself connects to the UML switch managing the
.IR DOMAIN .
The packet capture can be dumped to a file and viewed in a utility like
.BR tcpdump (8)
or
.BR wireshark (1),
or observed live (see
.BR EXAMPLES ).
The capture can safely be terminated with a keyboard interrupt signal
.RB ( Ctrl-C ).
.SH OPTIONS
.SS Miscellaneous options
.TP
.B \-\-help
Display a usage message and exit.
.TP
.BR \-v ", " \-\-verbose
Show the commands being ran.
To avoid mixing messages with the packet dump output,
all verbose output will be redirected to standard error.
.TP
.B \-\-version
Output version information and exit.
.SH ENVIRONMENT
.TP
.B NETKIT_HOME
All Netkit-JH commands require that the
.B NETKIT_HOME
variable is set the path of the directory which Netkit-JH is installed in.
.SH FILES
.TP
.I netkit.conf
.TQ
.BI NETKIT_HOME /netkit.conf.default
Netkit-JH stores its configuration settings inside a file named
.IR netkit.conf ,
which can be placed in up to three locations to change its scope.
The default settings are assigned in
.IR netkit.conf.default ;
the existence of this file is required in order to make Netkit-JH work.
See
.BR netkit.conf (5)
for information about these files.
.SH EXAMPLES
The following examples use
.B vdump
to capture packets from the virtual collision domain \(dqA\(dq.
The basic usage would be dumping the packets to a PCAP file for analysis later:
.nf
.IP
.BR vdump " A > capture.pcap"
.fi
.PP
.BR tcpdump (8)
can display packets live as they traverse across the hub:
.nf
.IP
.BR vdump " A | " \c
.BR tcpdump " \-r \-"
.fi
.PP
Similarly,
.BR wireshark (1)
can do the same for viewing the packets graphically:
.nf
.IP
.BR vdump " A | " \c
.BR wireshark " \-i \- \-k"
.fi
.SH AUTHORS
.so include/authors.man
.SH "SEE ALSO"
.BR vstart (1),
.BR wireshark (1),
.BR netkit.conf (5),
.BR netkit-jh (7),
.BR tcpdump (8)
