.TH VLIST 1 2022-09-01 Linux "Netkit-JH Manual"
.SH NAME
vlist \- show information about running Netkit-JH machines
.SH SYNOPSIS
.B vlist
.RI [ OPTION "]... [" MACHINE ]...
.SH DESCRIPTION
Provide a summary of running Netkit-JH virtual machines or get detailed
information about them.
If invoked with no non-option arguments,
.B vlist
shows a simple list of running virtual machines providing the machines' owner,
hostname, process ID, memory usage, and network interfaces.
Providing a list of
.IR MACHINE s
outputs more detailed information about each machine which covers each
parameter of
.BR vstart (1).
The following values are displayed:
.SS Accounting information
.TP
.B PID
The UML virtual machine's primary process ID.
Killing this will kill the entire machine.
.TP
.B Owner
Username of the process owner.
.TP
.B Used mem
Memory used by all of the virtual machine's processes on the host,
in kilobytes.
.SS Emulation parameters
.TP
.B Kernel
Path to the UML executable.
.TP
.B Modules
Path to the optional kernel modules directory.
.TP
.B Memory
Amount of memory available inside the virtual machine, in megabytes.
.TP
.B Model fs
Location of the model (backing) filesystem used by the machine.
.TP
.B Filesystem
Location of the machine's copy-on-write (COW) filesystem used during runtime.
.TP
.B Interfaces
List of network interfaces on the virtual machine,
including what collision domain they are on and the socket file of said
collision domain used by
.BR uml_switch .
.TP
.B Hostlab
Path to the lab directory (if launched as a lab) on the host.
.TP
.B Hosthome
Path to the host's home directory if mounted in the virtual machine.
.TP
.B Boot command
Name of the command executed by the machine during the boot phase.
.TP
.B Console 1
.TQ
.B Console 2
What the primary and secondary consoles of the virtual machine are attached to.
.TP
.B Other arguments
Additional arguments used in the kernel executable's command line.
.TP
.B Console socket
Path to the temporary socket file used by the UML management console.
.SH OPTIONS
.SS General options
.TP
.BR \-n ", " \-\-no\-header
Suppress the header line when using
.B vlist
with no non-option arguments.
.TP
.BR \-u ", " \-\-user =\fIUSERNAME\fR
Show machines owned by a different user.
The special username
.B \-
denotes all users.
By default, machines owned by the current user are shown.
.SS Miscellaneous options
.TP
.B \-\-help
Display a usage message and exit.
.TP
.B \-\-version
Output version information and exit.
.SH ENVIRONMENT
.TP
.B NETKIT_HOME
All Netkit-JH commands require that the
.B NETKIT_HOME
variable is set the path of the directory which Netkit-JH is installed in.
.SH FILES
.TP
.I netkit.conf
.TQ
.BI NETKIT_HOME /netkit.conf.default
Netkit-JH stores its configuration settings inside a file named
.IR netkit.conf ,
which can be placed in up to three locations to change its scope.
The default settings are assigned in
.IR netkit.conf.default ;
the existence of this file is required in order to make Netkit-JH work.
See
.BR netkit.conf (5)
for information about these files.
.SH AUTHORS
.so include/authors.man
.SH "SEE ALSO"
.BR vstart (1),
.BR netkit.conf (5),
.BR netkit-jh (7)
