.TH VSTART 1 2022-09-02 Linux "Netkit-JH Manual"
.SH NAME
vstart \- launch a new Netkit-JH machine
.SH SYNOPSIS
.B vstart
.RI [ OPTION "]... " MACHINE
.SH DESCRIPTION
Start
.I MACHINE
with a given configuration.
Names of virtual machines must be unique per user.
.PP
Invoking with no option arguments will launch the machine with a configuration
reflecting the variables defined inside the Netkit-JH configuration file\(emsee
.BR netkit.conf (5).
.SH OPTIONS
.SS General options
.TP
.BR \-\-append =\fIPARAM\fR
Append additional arguments to the UML kernel's command line.
Since
.I PARAM
is added unprocessed to the command, it can be an
.IR OPTION = VALUE
pair.
.B \-\-append
can be repeated;
parameters will be added in the same order in which they are provided.
Documentation regarding supported kernel command-line parameters can be found
in the kernel source tree.
.TP
.B \-\-debug
Run the virtual machine under a GDB instance to report more log messages than
.B \-\-show\-boot\-log
and to allow further debugging.
This process requires a
.B SIGINT
delivery
.RI ( "kill -INT PID" )
to start debugging.
.TP
.BR \-e ", " \-\-exec =\fICMD\fR
Run
.I CMD
during the second boot phase (see
.IR /etc/netkit/netkit-phase2 ).
.TP
.BR -F ", " \-\-foreground
Do not launch machines in the background.
This is implictly enabled when the console mode is
.BR this .
.TP
.BR \-n ", " \-\-dry\-run ", " \-\-just\-print ", " \-\-recon
Do not run any command, just show what would get executed.
.TP
.BR \-\-show\-boot\-log
Do not hide the Linux boot log in the virtual machine with the \(dqquiet\(dq
kernel argument.
This option is useful for quickly finding boot sequence errors.
.SS Kernel settings
.TP
.BR \-k ", " \-\-kernel =\fIFILE\fR
Use
.I FILE
as the UML kernel executable for the virtual machine.
The default path is the
.B VM_KERNEL
configuration variable.
.TP
.BR \-M ", " \-\-mem =\fIMEM\fR
Give the virtual machine
.I MEM
MB of RAM.
Permitted values range from
.B MIN_MEM
MB to
.B MAX_MEM
MB, defaulting to
.B VM_MEMORY
MB.
.SS Networking settings
.TP
.BR \-\-eth \fIN\fR=\fIDOMAIN\fR
Add a network interface called
.RI \(dqeth N \(dq,
where
.I N
is a number between 0 and
.BI MAX_INTERFACES \-1
inclusive.
.I DOMAIN
is the Netkit-JH collision domain that the interface should be attached to.
Special TAP domains may also be created with the following syntax:
.nf
.RS
.IP
.BR \-\-eth \fIN\fR=\fIDOMAIN\fR,\fITAP_ADDR\fR,\fIGUEST_ADDR\fR
.RE
.fi
.IP
where
.I DOMAIN
is a valid collision domain name,
.I TAP_ADDR
is the IP address of the host's TAP interface, and
.I GUEST_ADDR
is the IP address of the regular interface inside the virtual machine.
.IR TAP_ADDR " and " GUEST_ADDR
must be on the same /24 subnetwork.
Machines can share a TAP interface by using the same
.IR DOMAIN " and " TAP_ADDR
however, like with any regular subnetwork, issues will arise if they have equal
.IR GUEST_ADDR s.
Two interfaces cannot be created on the same
.I DOMAIN
but with different
.IR TAP_ADDR s.
Also, another interface cannot use a
.I TAP_ADDR
within the same /24 subnetwork as another;
there is currently no error checking for this.
.IP
Note: management of TAP interfaces requires administrative privileges since the
host's network interface and firewall configurations are modified;
the script will only elevate privileges where necessary.
TAP configurations on the host are not automatically removed when halting
machines, the
.BR vclean (1)
utility must be used for this purpose.
.SS Filesystem settings
.TP
.BR \-H ", " \-\-no\-hosthome
Do not mount the user's
.B HOME
directory on the host to
.I /hosthome/
inside the virtual machine.
.TP
.BR \-\-mount =\fISRC\fR,\fIDST\fR
Mount
.I SRC
directory from the host to
.I DST
directory (created if it does not exist) inside the virtual machine.
.TP
.BR \-m ", " \-\-model\-fs =\fIFILE\fR
Use
.I FILE
as a model filesystem for the virtual machine.
This is the filesystem the machine uses before any modifications are made by
the user.
The default is
.BR VM_MODEL_FS .
Since the machines each have their own copy-on-write (COW) filesystem,
.I FILE
will not be altered in any way unless the
.B \-\-no\-cow option is used.
For more information on UML's filesystems, see
.BR netkit-jh (7).
.TP
.BR \-f ", " \-\-filesystem =\fIFILE\fR
Use
.I FILE
as the machine's COW filesystem.
By default, this is
.IR MACHINE.disk .
The option is incompatible with
.BR \-\-no\-cow .
For more information on UML's COW filesystems, see
.BR netkit-jh (7).
.TP
.BR \-D ", " \-\-hide\-disk\-file
Delete the COW filesystem
.RI ( .disk " file)"
as soon as it is created.
This will not affect the virtual machine's functionality,
however will mean any changes are lost between subsequent launches of the
machine.
The option is incompatible with
.BR \-\-no\-cow .
.TP
.BR \-W ", " \-\-no\-cow
Do not use a COW filesystem.
Instead, every change to the virtual machine's filesystem is applied directly
to the model filesystem.
Never launch multiple machines using the same model filesystem.
This option is incompatible with
.BR \-\-filesystem " and " \-\-hide\-disk\-file .
.SS Console settings
.TP
.BR \-\-con0 =\fIMODE\fR
.TQ
.BR \-\-con1 =\fIMODE\fR
Attach the virtual machine's primary and secondary consoles, respectively, to a
different device.
Permitted values for
.I MODE
are:
.RS
.TP
.B xterm
Attach to a terminal emulator application.
.TP
.B this
Use the current terminal by attaching to standard input/output.
Only one console can use this option.
.TP
.B tmux
Run in a
.BR tmux (1)
session (only valid with
.BR \-\-con0 ).
The session will be attached to in a new window if
.B TMUX_OPEN_TERMS
is set to
.BR yes ,
otherwise it can be attached to later with
.BR vconnect (1).
See
.BR \-\-tmux\-attached / \-\-tmux\-detached
for more information on controlling automatic attachment to the session.
.TP
.B pty
Attach to a pseudoterminal.
This can later be attached to by connecting a terminal emulator to the
corresponding terminal, for example with
.IR "screen /dev/tty" N.
.TP
.BI port: N
Attach to TCP port
.IR N .
This can then be accessed by telnetting to that port.
The virtual machine will not be actually started until the first connection is
established,
and closing the connection will kill the server until the machine is restarted.
.TP
.B none
Disable the console.
.RE
.IP
The default console modes are set in the
.BR VM_CON0 " and " VM_CON1
configuration variables.
.TP
.B \-\-tmux\-attached
Implicitly use the
.B tmux
primary console mode and attach a new window of the chosen terminal emulator
to the tmux session.
This is equivalent to
.IR VM_CON0=tmux " and " TMUX_OPEN_TERMS=yes .
.TP
.B \-\-tmux\-detached
Implicitly use the
.B tmux
primary console mode but do not attach to the session.
This is useful if the user wishes to attach later or in their current terminal
session.
It is equivalent to
.IR VM_CON0=tmux " and " TMUX_OPEN_TERMS=no .
.TP
.BR \-\-xterm =\fITYPE\fR
Specify the terminal emulator application when the console mode is
.BR xterm .
The application must be installed on the host system.
Supported values are:
.RS
.TP
.B alacritty
The lightweight and hardware-accelerated Alacritty terminal.
.TP
.B gnome
Use the GNOME Terminal, GNOME's default terminal emulator.
.TP
.B kitty
kitty is a similar alternative to Alacritty.
.TP
.B kitty\-tab
Same as
.B kitty
but different machiens are opened in different tabs of the same window.
.TP
.B konsole
Use Konsole, KDE's default terminal emulator.
.TP
.B wsl
Use Windows Subsystem for Linux (WSL) with the default Windows terminal
emulator.
This is traditionally the Windows Console Host,
.BR conhost.exe ,
but modern systems may use Windows Terminal.
.TP
.B wt
Use Windows Subsystem for Linux (WSL) with the Windows Terminal terminal
emulator.
.TP
.B xterm
Use xterm, the most compatible terminal emulator.
.RE
.IP
The default terminal emulator is specified in the
.B TERM_TYPE
configuration variable.
.SS Netkit-JH lab options
Generally, these options should not be used. Instead, the lcommands should be
used to manage labs. See
.BR lstart (1)
for more information.
.TP
.BR \-l ", " \-\-hostlab =\fIDIR\fR
Mount
.I DIR
to
.I /hostlab/
inside the machine and signify to it that it is part of a Netkit-JH lab
(which runs further commands in the startup scripts).
.SS Miscellaneous options
.TP
.B \-\-help
Display a usage message and exit.
.TP
.BR \-v ", " \-\-verbose
Show details about the virtual machine when launching it.
.TP
.B \-\-version
Output version information and exit.
.SH ENVIRONMENT
.TP
.B NETKIT_HOME
All Netkit-JH commands require that the
.B NETKIT_HOME
variable is set the path of the directory which Netkit-JH is installed in.
.SH FILES
.TP
.I MACHINE.disk
This is the default COW filesystem used by virtual machines.
If it does not already exist, it is created in the current directory when
.I MACHINE
boots.
It stores all of the differences between the model filesystem and the current
filesystem contents, allowing persistent changes to be kept across reboots.
.SH AUTHORS
Netkit-JH is maintained by Adam Bromiley, Joshua Hawking,
and other important contributors who are current or graduate students of WMG,
University of Warwick.
A full list of contributors can be found in copyright notices at the top of
source files.
.PP
Netkit-JH is a fork of the now deprecated Netkit-NG,
maintained by Julien Iguchi-Cartigny of the XLIM Research Institute,
which itself is a fork of the original project (Netkit).
Netkit was written by academics at the Computer Networks Laboratory of Roma Tre
University before being abandoned in favour of Kathará,
which utilises Python and Docker instead of Bash and UML.
All iterations of Netkit have introduced important new features and upgraded
existing ones.
.SH "REPORTING BUGS"
To report a bug with Netkit-JH,
please create an issue with the recommended template on the project's
.UR https://github.com/netkit-jh/netkit-jh-build/issues
GitHub repository
.UE .
For a more complex bug that you know how to fix,
please consider writing a patch and sending it as a pull request to the GitHub.
.SH COPYRIGHT
Like its predecessors,
Netkit-JH is released under the terms of the GNU General Public License,
version 3 or later. For a copy of the license see the included
.I LICENSE.txt
file or, if not present,
.UR http://www.gnu.org/licenses/
.UE .
.SH "SEE ALSO"
.BR lstart (1),
.BR vclean (1),
.BR vcommand (1),
.BR vconf (1),
.BR vconnect (1),
.BR vcrash (1),
.BR vhalt (1),
.BR netkit.conf (5),
.BR netkit-jh (7)
