Netkit-JH is maintained by Adam Bromiley, Joshua Hawking,
and other important contributors who are current or graduate students of WMG,
University of Warwick.
A full list of contributors can be found in copyright notices at the top of
source files.
.PP
Netkit-JH is a fork of the now deprecated Netkit-NG,
maintained by Julien Iguchi-Cartigny of the XLIM Research Institute,
which itself is a fork of the original project (Netkit).
Netkit was written by academics at the Computer Networks Laboratory of Roma Tre
University before being abandoned in favour of Kathará,
which utilises Python and Docker instead of Bash and UML.
All iterations of Netkit have introduced important new features and upgraded
existing ones.
.PP
The Netkit-JH team greatly appreciates the work of all previous and current
maintainers.
.SH "REPORTING BUGS"
To report a bug with Netkit-JH,
please create an issue with the recommended template on the project's
.UR https://github.com/netkit-jh/netkit-jh-build/issues
GitHub repository
.UE .
For a more complex bug that you know how to fix,
please consider writing a patch and sending it as a pull request to the GitHub.
.SH COPYRIGHT
Like its predecessors,
Netkit-JH is released under the terms of the GNU General Public License,
version 3 or later. For a copy of the license see the included
.I LICENSE.txt
file or, if not present,
.UR http://www.gnu.org/licenses/
.UE .
