#!/bin/bash

#     Copyright 2002-2007 Maurizio Patrignani, Stefano Pettini, Maurizio Pizzonia,
#     Fabio Ricci, Massimo Rimondini - Computer Networks Research Group, Roma Tre
#     University.
#
#     This file is part of Netkit.
#
#     Netkit is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     Netkit is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with Netkit.  If not, see <http://www.gnu.org/licenses/>.

### BEGIN INIT INFO
# Provides:          netkit-phase2
# Required-Start:    netkit-phase1 
# Required-Stop:     netkit-phase1 
# Should-Start:      networking
# Should-Stop:       networking
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Netkit phase 2
# Description:       This is a Netkit initialization script. It is intended for
#                    usage inside virtual machines.
### END INIT INFO

# ANSI style escape sequences
DELIMITER_TEXT=$'\e[34;1m'
NORMAL_TEXT=$'\e[0m\e[34m'
PLAIN_TEXT=$'\e[0m'
INFO_FIELD=$'\e[34;1m'

# Variables from the kernel command line (used by both start and stop,
# namely $HOSTNAME - we don't trust what happens to $HOSTNAME within system)
ASSIGN_VARIABLES=`cat /proc/cmdline | awk -v FS== -v RS=' ' \
    '
                    ($1=="name") {print "HOSTNAME=" $2}
                    ($1=="hostlab") {print "HOSTLAB=" $2}
                    ($1=="exec") {print "COMMAND=" $2}
                    ($1=="test") {print "TEST=" $1}
                    '`
eval "$ASSIGN_VARIABLES"

# these may be used by scripts that we call
export HOSTNAME
export HOSTLAB

case "$1" in
   start) 
      echo
      echo "${DELIMITER_TEXT}--- Starting Netkit phase 2 init script ---${NORMAL_TEXT}"

      if [ -f /hostlab/shared.startup ]; then
         echo
         echo ">>> Running shared startup script..."
         /bin/sh -c '. /hostlab/shared.startup'
         echo ">>> End of shared startup script."
         echo
      fi

      if [ -f /hostlab/$HOSTNAME.startup ]; then
         echo
         echo ">>> Running $HOSTNAME specific startup script..."
         /bin/sh -c ". /hostlab/$HOSTNAME.startup"
         echo ">>> End of $HOSTNAME specific startup script."
         echo
      fi

      if [ -x "$COMMAND" ]; then
         echo "Executing $COMMAND ..."
         $COMMAND
      fi



      if [ -d /hostlab ]; then
         # Read lab configuration file, if present
         if [ -r "/hostlab/lab.conf" ]; then
            # Filter out unuseful (and potentially invalid) lab.conf contents.
            eval `grep -E "(LAB_VERSION)|(LAB_AUTHOR)|(LAB_EMAIL)|(LAB_WEB)|(LAB_DESCRIPTION)" /hostlab/lab.conf`
         fi

         : ${LAB_VERSION:="<none>"}
         : ${LAB_AUTHOR:="<none>"}
         : ${LAB_EMAIL:="<none>"}
         : ${LAB_WEB:="<none>"}
         : ${LAB_DESCRIPTION:="<none>"}

         echo
         echo "${DELIMITER_TEXT}##################################################${NORMAL_TEXT}"
         echo
         echo "${INFO_FIELD}Lab directory (host)${NORMAL_TEXT}: $HOSTLAB"
         echo "${INFO_FIELD}Version${NORMAL_TEXT}: $LAB_VERSION"
         echo "${INFO_FIELD}Author${NORMAL_TEXT}:  $LAB_AUTHOR"
         echo "${INFO_FIELD}Email${NORMAL_TEXT}:   $LAB_EMAIL"
         echo "${INFO_FIELD}Web${NORMAL_TEXT}:     $LAB_WEB"
         echo "${INFO_FIELD}Description${NORMAL_TEXT}:"
         echo "$LAB_DESCRIPTION"
         echo
         echo "${DELIMITER_TEXT}##################################################${NORMAL_TEXT}"
         echo
         touch /hostlab/$HOSTNAME.ready
      fi


      if [ ! -z "$TEST" ]; then
         /sbin/netkit-test-phase
      fi
      

      echo "${DELIMITER_TEXT}--- Netkit phase 2 initialization terminated ---${PLAIN_TEXT}"
      echo
      ;;

   stop)
      echo
      echo "${DELIMITER_TEXT}--- Starting Netkit phase 2 shutdown script ---${NORMAL_TEXT}"

      if [ -f /hostlab/$HOSTNAME.shutdown ]; then
         echo
         echo ">>> Running $HOSTNAME specific shutdown script..."
         /bin/sh -c ". /hostlab/$HOSTNAME.shutdown"
         echo ">>> End of $HOSTNAME specific shutdown script."
         echo
      fi

      if [ -f /hostlab/shared.shutdown ]; then
         echo
         echo ">>> Running shared shutdown script..."
         /bin/sh -c '. /hostlab/shared.shutdown'
         echo ">>> End of shared shutdown script."
         echo
      fi

      
      echo "${DELIMITER_TEXT}--- Netkit shutdown phase 2 terminated ---${PLAIN_TEXT}"
      echo
      ;;

   *)
      echo "Usage: $0 {start|stop}"
      exit 1
      ;;

esac

