#!/usr/bin/env bash

#     Copyright 2020-2022 Adam Bromiley, Joshua Hawking - Warwick Manufacturing
#     Group, University of Warwick.
#     Copyright 2002-2007 Maurizio Patrignani, Stefano Pettini, Maurizio
#     Pizzonia, Fabio Ricci, Massimo Rimondini - Computer Networks Research
#     Group, Roma Tre University.
#
#     This file is part of Netkit.
#
#     Netkit is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     Netkit is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with Netkit.  If not, see <http://www.gnu.org/licenses/>.


### BEGIN INIT INFO
# Provides:          netkit-phase2
# Required-Start:    netkit-phase1 
# Required-Stop:     netkit-phase1 
# Should-Start:      networking
# Should-Stop:       networking
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Netkit phase 2
# Description:       This is a Netkit initialization script. It is intended for
#                    usage inside virtual machines.
### END INIT INFO


###############################################################################
# Write netkit-phase2's usage line to standard output.
# Usage:
#   usage_line
###############################################################################
usage_line() {
   echo "Usage: $SCRIPTNAME {start|stop}"
}


###############################################################################
# Get the value of a parameter set in a lab's lab.conf file and write to
# standard output.
# Usage:
#   get_lab_variable VARIABLE DIR
# Arguments:
#   $1 - lab variable name
#   $2 - lab directory
###############################################################################
get_lab_variable() {
   local variable=$1
   local lab_conf="$2/lab.conf"

   # Set lab variables from lab.conf. The sed expression prints only the first
   # matching line and deletes the variable name and equals sign.
   value=$(sed --quiet -- "0,/^$variable=/s///p" "$lab_conf")
   printf "%s\n" "${value:-"<unknown>"}"
}


SCRIPTNAME=$(basename -- "$0")


# ANSI color escape sequences
color_normal=$'\033[0m'
color_bold_blue=$'\033[34;1m'
color_cyan=$'\033[36m'


# Hostname has been set in netkit-phase1
hostname=$(hostname)


# This short GNU AWK script processes /proc/cmdline (the command line used to
# invoke the kernel). The script transforms it into a null-delimited list of
# parameters by replacing all unquoted spaces with a null byte, making the
# output similar to /proc/$pid/cmdline. The kernel_cmd variable is a Bash array
# where each element is a parameter=value specification.
mapfile -d "" -t kernel_cmd < <(gawk '
   BEGIN {
      FPAT = "([^ ]+)|(\"[^\"]+\")"
      OFS = "\0"
   }
   {
      $1=$1
      gsub("\"", "")
      printf $0
   }' < /proc/cmdline)

for arg in "${kernel_cmd[@]}"; do
   opt=${arg%%=*}
   value=${arg#*=}

   case $opt in
      hostlab) hostlab=$value;;
      exec)    exec_cmd=${value#*,};;
      test)    test_delay=$value;;
   esac
done


case $1 in
   start)
      echo
      echo "$color_bold_blue--- Starting Netkit phase 2 init script ---$color_normal$color_cyan"


      if [ -f /hostlab/shared.startup ]; then
         echo
         echo ">>> Running shared startup script..."
         bash /hostlab/shared.startup
         echo ">>> End of shared startup script."
         echo
      fi

      if [ -f "/hostlab/$hostname.startup" ]; then
         echo
         echo ">>> Running $hostname specific startup script..."
         bash "/hostlab/$hostname.startup"
         echo ">>> End of $hostname specific startup script."
         echo
      fi


      if [ -n "$exec_cmd" ]; then
         echo "Executing $exec_cmd"
         $exec_cmd
      fi


      if [ -d /hostlab/ ]; then
         # We ignore errors (missing lab.conf) in the case where the lab was
         # force-started.
         lab_version=$(get_lab_variable "LAB_VERSION" "/hostlab/" 2> /dev/null)
         lab_author=$(get_lab_variable "LAB_AUTHOR" "/hostlab/" 2> /dev/null)
         lab_email=$(get_lab_variable "LAB_EMAIL" "/hostlab/" 2> /dev/null)
         lab_web=$(get_lab_variable "LAB_WEB" "/hostlab/" 2> /dev/null)
         lab_description=$(get_lab_variable "LAB_DESCRIPTION" "/hostlab/" 2> /dev/null)

         echo
         echo "$color_bold_blue##################################################"
         echo
         echo                   "Lab directory: $color_normal$color_cyan$hostlab"
         echo "${color_bold_blue}Version:       $color_normal$color_cyan$lab_version"
         echo "${color_bold_blue}Author:        $color_normal$color_cyan$lab_author"
         echo "${color_bold_blue}Email:         $color_normal$color_cyan$lab_email"
         echo "${color_bold_blue}URL:           $color_normal$color_cyan$lab_web"
         echo "${color_bold_blue}Description:"
         echo "$color_normal$color_cyan$lab_description"
         echo
         echo "$color_bold_blue##################################################$color_normal"
         echo

         touch "/hostlab/$hostname.ready"
      fi


      [ -n "$test_delay" ] && /etc/netkit/netkit-test-phase "$test_delay"


      echo "$color_bold_blue--- Netkit phase 2 initialization terminated ---$color_normal"
      echo
      ;;
   stop)
      echo
      echo "$color_bold_blue--- Starting Netkit phase 2 shutdown script ---$color_normal$color_cyan"


      if [ -f "/hostlab/$hostname.shutdown" ]; then
         echo
         echo ">>> Running $hostname specific shutdown script..."
         bash "/hostlab/$hostname.shutdown"
         echo ">>> End of $hostname specific shutdown script."
         echo
      fi

      if [ -f /hostlab/shared.shutdown ]; then
         echo
         echo ">>> Running shared shutdown script..."
         bash /hostlab/shared.shutdown
         echo ">>> End of shared shutdown script."
         echo
      fi


      echo "$color_bold_blue--- Netkit shutdown phase 2 terminated ---$color_normal"
      echo
      ;;
   *)
      usage_line
      exit 1
      ;;
esac
